"""Add return columns to holding table

Revision ID: b479c4bd6275
Revises: 
Create Date: 2025-02-22 21:41:58.395255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b479c4bd6275'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_return', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('return_percentage', sa.Float(), nullable=True))
        batch_op.alter_column('purchase_price',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.alter_column('purchase_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_column('return_percentage')
        batch_op.drop_column('total_return')

    # ### end Alembic commands ###
